### ISSUE TITLE
Small change needed for recompile on Marmalade 7.5

### ISSUE THREAD

**Issue by tipam** [marmalade/Freetype#1]
Compiling Freetype library in Marmalade 7.5.1 causes an error ...

Error cause:      IwGxSetUVStream no longer accepts CIwSVec2 as a parameter.

Fix:

In fthGlyphLayoutData.h (line 32);

<code>  CIwArray<CIwSVec2> renderBufferUV; </code>   must be changed to
<code>  CIwArray<CIwFVec2> renderBufferUV; </code>

and,

In fthFont.cpp (line 493);

<code>   CIwSVec2\* uv = &renderBufferUV.front();</code>  must be changed to 
<code>   CIwFVec2\* uv = &renderBufferUV.front();</code>

Secondly, when compiling with GCC, the following error(s) are reported:

freetypehelper.cpp(27) ::_GetCfthFontSize()' (col  undefined reference to `FreeTypeHelper)

To fix this error:

In fthFont.cpp (from line 11) change;

![fh1](https://cloud.githubusercontent.com/assets/1822521/6668736/b04b9908-cbec-11e4-939e-a40f575cf181.png)

to

![ft2](https://cloud.githubusercontent.com/assets/1822521/6668741/bb96721a-cbec-11e4-8335-213822ade500.png)

... this is because the class factory is not created within the FreeTypeHelper namespace.

PLEASE NOTE this workaround will not work with 'x86 Debug' - I still haven't had time to work out why - sorry!!
